@ApiGateway_HostAddress = http://localhost:5146

### Create category

POST {{ApiGateway_HostAddress}}/categories/
Accept: application/json
Content-Type: application/json

{
  "name": "Art"
}

### List categories

GET {{ApiGateway_HostAddress}}/categories/
Accept: application/json

### List projects with page

GET {{ApiGateway_HostAddress}}/projects/page
Accept: application/json

### List projects with offset and limit

GET {{ApiGateway_HostAddress}}/projects/offset-limit
Accept: application/json

### List projects with keyset

GET {{ApiGateway_HostAddress}}/projects/keyset?pageSize=3&startAfter=1042m6hp8m100g8
Accept: application/json

### List projects with page token

GET {{ApiGateway_HostAddress}}/projects/page-token?sort=title&maxPageSize=3&pageToken=P80QKV1WG21KAMYJ4BWF4X9SQR1SPF8M451K0DTW6SWXW3KF4KJVZQ9SC56QM0W4WJD10152V18G0

### Create account

POST {{ApiGateway_HostAddress}}/accounts/
Accept: application/json
Content-Type: application/json

{
  "name": "John Doe",
  "email": "John@doe.com",
  "password": "Pass1123"
}

### Get deposit address

GET {{ApiGateway_HostAddress}}/crypto-payments/addresses/
Accept: application/json
