@ApiGateway_HostAddress = http://localhost:5146

### Create category

POST {{ApiGateway_HostAddress}}/categories/
Accept: application/json
Content-Type: application/json

{
  "name": "Art"
}

### List categories

GET {{ApiGateway_HostAddress}}/categories/
Accept: application/json

### List projects

GET {{ApiGateway_HostAddress}}/projects?maxPageSize=3&pageToken=7S4EYnn1yBqsCIf-R4ETA9Nc3HWz3AuEZuJ1Ama1Pxb22qfao97MTo79VF5SmqFJ
Accept: application/json

### Create account

POST {{ApiGateway_HostAddress}}/accounts/
Accept: application/json
Content-Type: application/json

{
  "name": "John Doe",
  "email": "John@doe.com",
  "password": "Pass1123"
}

### Get deposit address

GET {{ApiGateway_HostAddress}}/crypto-payments/addresses/
Accept: application/json
