@ApiGateway_HostAddress = http://localhost:5146

### Create category

POST {{ApiGateway_HostAddress}}/categories/
Accept: application/json
Content-Type: application/json

{
  "name": "Art"
}

### List categories

GET {{ApiGateway_HostAddress}}/categories/
Accept: application/json

### List projects

GET {{ApiGateway_HostAddress}}/projects?sort=-title&pageToken=KJS97GGB5DS42D4SETX2XGQam04ST5GF96BH77Y7EG0RJTZCHWQXWMWXK8TR2CRZY673XE8V5S6RT
Accept: application/json

### Create account

POST {{ApiGateway_HostAddress}}/accounts/
Accept: application/json
Content-Type: application/json

{
  "name": "John Doe",
  "email": "John@doe.com",
  "password": "Pass1123"
}

### Get deposit address

GET {{ApiGateway_HostAddress}}/crypto-payments/addresses/
Accept: application/json
